### ISSUE TITLE
Question: Connection and creation a user

### ISSUE THREAD

**Issue by OlegBodyansky** [upmind-automation/provision-provider-website-builders#2]
Hello, I have stuck with the connection to upmind.
I created account at upmind.
`$configuration = [
    'api_url' => 'https://rest.bk-partnersus.com/',
    'username' => '{username}',
    'password' => '{password}',
    'brand_ref' => '{brand ref}',
    'suspension_package_ref' => '{suspension package ref}',
];`
What is api_url which user name and password I should use?
where does brand_ref  save?
Response return null if I use my upmind link and my user data for login

**Comment by uphlewis** [comment]
Hi Oleg!

You'd need to get these credentials from BaseKit, as this package is only for consuming the BaseKit API.

Hope that helps.

**Comment by OlegBodyansky** [comment]
**face_palm** thanks I'll try

**Comment by uphlewis** [comment]
Great! By the way if you haven't seen it already we've recently published a tool which really simplifies the development/testing flow for provision providers which i'd highly recommend trying out: https://github.com/upmind-automation/provision-workbench#readme

Otherwise, if you're just trying to set up BaseKit products in your Upmind instance i'd recommend following this guide: https://docs.upmind.com/docs/how-to-integrate-and-sell-basekit

If you run into any problems or require any assistance on the Upmind side please raise a support ticket from your Upmind instance by clicking the Help button in the top bar of your admin area.

Thanks :)
